#!/usr/bin/env bash
# Installing Nginx on ubuntu where it should be listening on port 80
# Serve a page that would return a Hello World string

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# start nginx service
sudo service nginx start

# allow nginx on the firewall
sudo ufw allow 'Nginx HTTP'

# Create a new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Backup the default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Give user ownership to the website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Restart the nginx
sudo service nginx restart

echo -e "\nCompleted.\n"
