#!/usr/bin/env bash
# configuration of a server to listening on port 80 of all servers active IPv4 IPs

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
echo "" | sudo dd status=none of=/run/nginx.pid
#restarting the nginx
sudo service nginx restart
